### ISSUE TITLE
[FEATURE] Adding the particles effect

### ISSUE THREAD

**Issue by superiorsd10** [ziarparvaiz/github-dev#5]
Hey! 
The UI is looking good, but I can make it look even better. I want to add the interactive particle effect through `particle.js`. 
So please assign this issue to me.

**Comment by ziarparvaiz** [comment]
😊 Of course now we will write this with ReactJS and Tailwind CSS, it will take a few days if you can do it in ReactJS I can assign this issue for you.

**Comment by superiorsd10** [comment]
@ziarparvaiz Ok, I'll be doing that in React JS.

**Comment by ziarparvaiz** [comment]
@superiorsd10 Good Luck
